<?php

namespace App\Entity;

use App\Repository\SurvivalBenefitRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * SurvivalBenefit  a periodic payout from a Money Back policy.
 *
 * LIC Money Back plans pay a percentage of the Sum Assured at fixed
 * intervals during the policy term. This entity tracks each such
 * payout milestone so the agent can follow up with the client.
 *
 * Payout schedules (auto-generated by SurvivalBenefitGeneratorService):
 *   20-year plan → years 5, 10, 15 at 20 % of SA each
 *   25-year plan → years 5, 10, 15, 20 at 15 % of SA each
 */
#[ORM\Entity(repositoryClass: SurvivalBenefitRepository::class)]
class SurvivalBenefit
{
    // Status constants
    public const STATUS_PENDING   = 'PENDING';
    public const STATUS_COLLECTED = 'COLLECTED';
    public const STATUS_MISSED    = 'MISSED';

    public const STATUSES = [
        self::STATUS_PENDING   => 'Pending',
        self::STATUS_COLLECTED => 'Collected',
        self::STATUS_MISSED    => 'Missed',
    ];

    // Primary Key
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    // Relationships
    #[ORM\ManyToOne(inversedBy: 'survivalBenefits')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private ?Policy $policy = null;

    // Core Fields

    /** Date on which LIC pays this survival benefit. */
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $dueDate = null;

    /** Amount payable  typically a % of Sum Assured. */
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $amount = null;

    /** e.g. 20.00 means 20 % of SA. Stored for reference. */
    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $percentageOfSA = null;

    /** PENDING | COLLECTED | MISSED */
    #[ORM\Column(length: 20)]
    private ?string $status = self::STATUS_PENDING;

    /** Date agent confirmed client collected the benefit (nullable). */
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $collectedDate = null;

    /** Agent notes about collection (nullable). */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    // Audit Fields (Gedmo)
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Gedmo\Timestampable(on: 'create')]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Gedmo\Blameable(on: 'create')]
    private ?string $createdBy = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Gedmo\Timestampable(on: 'update')]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Gedmo\Blameable(on: 'update')]
    private ?string $updatedBy = null;

    // Business Logic Helpers

    /** Human-readable status label. */
    public function getStatusLabel(): string
    {
        return self::STATUSES[$this->status] ?? ($this->status ?? '-');
    }

    /** Amount as float (safe for arithmetic). */
    public function getAmountFloat(): float
    {
        return (float) ($this->amount ?? '0');
    }

    // Getters & Setters

    public function getId(): ?int { return $this->id; }

    public function getPolicy(): ?Policy { return $this->policy; }
    public function setPolicy(?Policy $policy): static { $this->policy = $policy; return $this; }

    public function getDueDate(): ?\DateTime { return $this->dueDate; }
    public function setDueDate(\DateTime $dueDate): static { $this->dueDate = $dueDate; return $this; }

    public function getAmount(): ?string { return $this->amount; }
    public function setAmount(string $amount): static { $this->amount = $amount; return $this; }

    public function getPercentageOfSA(): ?string { return $this->percentageOfSA; }
    public function setPercentageOfSA(string $percentageOfSA): static { $this->percentageOfSA = $percentageOfSA; return $this; }

    public function getStatus(): ?string { return $this->status; }
    public function setStatus(string $status): static { $this->status = $status; return $this; }

    public function getCollectedDate(): ?\DateTime { return $this->collectedDate; }
    public function setCollectedDate(?\DateTime $collectedDate): static { $this->collectedDate = $collectedDate; return $this; }

    public function getNotes(): ?string { return $this->notes; }
    public function setNotes(?string $notes): static { $this->notes = $notes; return $this; }

    public function getCreatedAt(): ?\DateTimeInterface { return $this->createdAt; }
    public function setCreatedAt(?\DateTimeInterface $createdAt): static { $this->createdAt = $createdAt; return $this; }

    public function getCreatedBy(): ?string { return $this->createdBy; }
    public function setCreatedBy(?string $createdBy): static { $this->createdBy = $createdBy; return $this; }

    public function getUpdatedAt(): ?\DateTimeInterface { return $this->updatedAt; }
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): static { $this->updatedAt = $updatedAt; return $this; }

    public function getUpdatedBy(): ?string { return $this->updatedBy; }
    public function setUpdatedBy(?string $updatedBy): static { $this->updatedBy = $updatedBy; return $this; }

    public function __toString(): string
    {
        $label = 'Survival Benefit';
        if ($this->dueDate) {
            $label .= ' - ' . $this->dueDate->format('d-M-Y');
        }
        if ($this->amount) {
            $label .= ' (₹' . number_format((float) $this->amount, 2) . ')';
        }
        return $label;
    }
}
